### ISSUE TITLE
[Parity] WebSocket over capacity, rejects connections

### ISSUE THREAD

**Issue by milankragujevic** [Paratii-Video/paratii-lib#112]
Two tests fail: 

```
  paratii.eth.events API: :
connection not open on send()
connection not open on send()
    1) "before all" hook: _callee

  paratii.eth API: :
connection not open on send()
connection not open on send()
    2) "before each" hook: _callee for "getContracts() should return the contracts"

```

```
  1) paratii.eth.events API: :
       "before all" hook: _callee:
     Error: connection not open
      at WebsocketProvider.send (node_modules/web3-providers-ws/src/index.js:219:18)
      at RequestManager.send (node_modules/web3-core-requestmanager/src/index.js:129:66)
      at sendSignedTx (node_modules/web3-core-method/src/index.js:499:35)
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:497:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:555:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:600:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:683:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:624:18)
      at Promise._resolveCallback (node_modules/bluebird/js/release/promise.js:424:57)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:17)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:555:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:600:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:683:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:624:18)
      at PromiseArray._resolve (node_modules/bluebird/js/release/promise_array.js:125:19)
      at PromiseArray._promiseFulfilled (node_modules/bluebird/js/release/promise_array.js:143:14)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:560:26)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:600:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:683:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:125:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:135:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:16:14)

  2) paratii.eth API: :
       "before each" hook: _callee for "getContracts() should return the contracts":
     Error: connection not open
      at WebsocketProvider.send (node_modules/web3-providers-ws/src/index.js:219:18)
      at RequestManager.send (node_modules/web3-core-requestmanager/src/index.js:129:66)
      at sendSignedTx (node_modules/web3-core-method/src/index.js:499:35)
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:497:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:555:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:600:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:683:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:624:18)
      at Promise._resolveCallback (node_modules/bluebird/js/release/promise.js:424:57)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:17)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:555:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:600:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:683:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:624:18)
      at PromiseArray._resolve (node_modules/bluebird/js/release/promise_array.js:125:19)
      at PromiseArray._promiseFulfilled (node_modules/bluebird/js/release/promise_array.js:143:14)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:560:26)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:600:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:683:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:125:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:135:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:16:14)



```

Meanwhile, Parity says: 

```
Unable to build WebSocket connection WS Error <Capacity>: Unable to add another connection to the event loop.
```

CentOS, installed as per @Leeaandrob's Dockerfile, on 2 Core 4GB RAM VM.

**Comment by geckoslair** [comment]
Possible workaround for this limitation (please integrate):
- [ ] optimize creation and destruction of listener during test (currently there's no documented way to destruct a listener on a contract)
- [ ] specialize different node for different events type (tx vs videos vs user)
- [ ] use just logs and not contract events
- [ ] create a contract that emit events for all type of event.

**Comment by jellegerbrandy** [comment]
An important observation is that on circleci the tests pass: https://circleci.com/gh/Paratii-Video/paratii-lib/375
while on milan (and mine) local machine they do not. So perhaps websockets are not closed quickly enough?

Another thing to look at is if (some of) our tests do not leave procesesses unresolved while exiting from the test. That may explain why webscockets remain open.

Yet another thing to look at: if we can tweak the number of open websockets that parity can handle.

**Comment by milankragujevic** [comment]
If it helps, here's a log of `parity` and `yarn test` ran together so that we can see when the error first occurs. 

[yarn-test-log-temp-2018-02-10-18-26.txt](https://github.com/Paratii-Video/paratii-lib/files/1713614/yarn-test-log-temp-2018-02-10-18-26.txt)

**Comment by milankragujevic** [comment]
Incredibly, branch `feat/persistent-ipfs` works just fine (https://github.com/Paratii-Video/paratii-lib/tree/feat/persistent-ipfs), so I think that the commit https://github.com/Paratii-Video/paratii-lib/commit/2975cf7500783f5707cc684aec37cbec190e9af4 broke stuff, I'm trying to figure out how...

**Comment by ya7ya** [comment]
@milankragujevic I think this has to do with the parity upgrades than our code, if you run the `mocha --require babel.js --exit --timeout 10000 test/paratii.eth.events.js` it works fine. the issue is IMO the unclosed web3 websocket connections from all the tests. That's why it works on circleCI where the processes are cleared faster apparently.

**Comment by milankragujevic** [comment]
I don't know, I tried with the same Parity as is on CircleCI, and it works every time with that old code... I don't know...

**Comment by ya7ya** [comment]
@milankragujevic good point. i did check `feat/persistent-ipfs` and it passed the tests..

**Comment by milankragujevic** [comment]
I managed to fix it locally, check out https://github.com/Paratii-Video/paratii-lib/tree/112_bug , waiting for tests to run. Basically Web3 thought it wasn't a testnet, and also we didn't await some calls to Paratii.
